alias cb='colcon build --cmake-args -Wno-dev --symlink-install'
alias cbr='colcon build --cmake-args -Wno-dev --symlink-install --clean'
alias so='. install/local_setup.bash'
alias rosd='rosdep install -i --from-path src --rosdistro humble -y'
alias up='sudo /home/giorgio/.my_sh/update.sh'
alias expy='/home/giorgio/.my_sh/make_py_executable.sh src'
